# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Rem0o.FanControl
PackageVersion: "188"
PackageLocale: en-US
Publisher: Remi Mercier Software Inc
PublisherUrl: https://github.com/Rem0o
PublisherSupportUrl: https://github.com/Rem0o/FanControl.Releases/issues
# PrivacyUrl:
Author: Rem0o
PackageName: FanControl
PackageUrl: https://getfancontrol.com/
License: Freeware
LicenseUrl: https://github.com/Rem0o/FanControl.Releases/blob/master/LICENSE
Copyright: © 2024 Rémi Mercier. All rights reserved.
CopyrightUrl: https://github.com/Rem0o/FanControl.Releases/blob/master/LICENSE
ShortDescription: A highly focused fan controlling software for Windows
Description: Fan Control is a free software that allows the user to control his CPU, GPU and case fans using temperatures.
# Moniker:
Tags:
- control
- cpu
- curve
- fan
- fancontrol
- gpu
- pwm
- speed
- temperature
ReleaseNotes: |-
  - Update LibreHardwareMonitorLib
  - Fix some auto-calibration issues
  - Do not queue snack messages when window is not visible
  - Detect control discrepancy with calibration
ReleaseNotesUrl: https://github.com/Rem0o/FanControl.Releases/releases/tag/V188
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://getfancontrol.com/docs/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
